/**
 * City suggestions for "Add new gym". A bundled list of Czech and Slovak towns (works offline,
 * no paid service) merged with cities already used by gyms in the database.
 */

const CZ = [
  'Praha',
  'Brno',
  'Ostrava',
  'Plzeň',
  'Liberec',
  'Olomouc',
  'České Budějovice',
  'Hradec Králové',
  'Ústí nad Labem',
  'Pardubice',
  'Zlín',
  'Havířov',
  'Kladno',
  'Most',
  'Opava',
  'Frýdek-Místek',
  'Jihlava',
  'Karviná',
  'Teplice',
  'Děčín',
  'Karlovy Vary',
  'Chomutov',
  'Jablonec nad Nisou',
  'Mladá Boleslav',
  'Prostějov',
  'Přerov',
  'Česká Lípa',
  'Třebíč',
  'Třinec',
  'Tábor',
  'Znojmo',
  'Kolín',
  'Příbram',
  'Cheb',
  'Trutnov',
  'Písek',
  'Orlová',
  'Kroměříž',
  'Vsetín',
  'Šumperk',
  'Uherské Hradiště',
  'Břeclav',
  'Hodonín',
  'Český Těšín',
  'Litvínov',
  'Havlíčkův Brod',
  'Nový Jičín',
  'Chrudim',
  'Krnov',
  'Litoměřice',
  'Sokolov',
  'Strakonice',
  'Valašské Meziříčí',
  'Klatovy',
  'Kopřivnice',
  'Jindřichův Hradec',
  'Kutná Hora',
  'Žďár nad Sázavou',
  'Bohumín',
  'Vyškov',
  'Blansko',
  'Náchod',
  'Brandýs nad Labem-Stará Boleslav',
  'Jirkov',
  'Žatec',
  'Kralupy nad Vltavou',
  'Louny',
  'Kadaň',
  'Hranice',
  'Otrokovice',
  'Benešov',
  'Svitavy',
  'Uherský Brod',
  'Rožnov pod Radhoštěm',
  'Jičín',
  'Ostrov',
  'Neratovice',
  'Pelhřimov',
  'Beroun',
  'Říčany',
  'Rakovník',
  'Mělník',
  'Boskovice',
  'Varnsdorf',
  'Bruntál',
  'Dvůr Králové nad Labem',
  'Slaný',
  'Kuřim',
  'Čelákovice',
  'Prachatice',
  'Domažlice',
  'Ústí nad Orlicí',
  'Rychnov nad Kněžnou',
  'Vysoké Mýto',
  'Česká Třebová',
  'Humpolec',
  'Kyjov',
  'Veselí nad Moravou',
  'Hlučín',
  'Nymburk',
  'Poděbrady',
  'Lysá nad Labem',
  'Roudnice nad Labem',
  'Bílina',
  'Rumburk',
  'Turnov',
  'Nové Město nad Metují',
  'Vrchlabí',
  'Hořice',
  'Lanškroun',
  'Polička',
  'Moravská Třebová',
  'Zábřeh',
  'Mohelnice',
  'Uničov',
  'Šternberk',
  'Lipník nad Bečvou',
  'Bystřice pod Hostýnem',
  'Holešov',
  'Luhačovice',
  'Frenštát pod Radhoštěm',
  'Studénka',
  'Bílovec',
  'Odry',
  'Frýdlant nad Ostravicí',
  'Jablunkov',
  'Rýmařov',
  'Jeseník',
  'Šlapanice',
  'Rosice',
  'Ivančice',
  'Tišnov',
  'Mikulov',
  'Hustopeče',
  'Slavkov u Brna',
  'Bučovice',
  'Moravský Krumlov',
  'Velké Meziříčí',
  'Telč',
  'Pacov',
  'Sušice',
  'Vimperk',
  'Český Krumlov',
  'Třeboň',
  'Dačice',
  'Milevsko',
  'Vodňany',
  'Rokycany',
  'Tachov',
  'Stříbro',
  'Přeštice',
  'Nýřany',
  'Mariánské Lázně',
  'Františkovy Lázně',
  'Aš',
  'Chodov',
  'Nejdek',
  'Kraslice',
  'Kaplice',
  'Sedlčany',
  'Votice',
  'Vlašim',
  'Hořovice',
  'Dobříš',
  'Černošice',
  'Jesenice',
  'Hostivice',
  'Unhošť',
  'Odolena Voda',
  'Kostelec nad Černými lesy',
  'Mnichovo Hradiště',
  'Bělá pod Bezdězem',
  'Nový Bor',
  'Frýdlant',
  'Chrastava',
  'Tanvald',
  'Železný Brod',
  'Semily',
  'Lomnice nad Popelkou',
  'Jaroměř',
  'Kostelec nad Orlicí',
  'Hlinsko',
  'Holice',
  'Přelouč',
  'Heřmanův Městec',
  'Chotěboř',
  'Světlá nad Sázavou',
  'Ledeč nad Sázavou',
  'Čáslav',
  'Uhlířské Janovice',
  'Mladá Vožice',
  'Soběslav',
  'Sezimovo Ústí',
  'Bechyně',
];

const SK = [
  'Bratislava',
  'Košice',
  'Prešov',
  'Žilina',
  'Nitra',
  'Banská Bystrica',
  'Trnava',
  'Trenčín',
  'Martin',
  'Poprad',
  'Prievidza',
  'Zvolen',
  'Považská Bystrica',
  'Michalovce',
  'Nové Zámky',
  'Spišská Nová Ves',
  'Komárno',
  'Levice',
  'Humenné',
  'Bardejov',
  'Liptovský Mikuláš',
  'Lučenec',
  'Piešťany',
  'Ružomberok',
  'Topoľčany',
  'Trebišov',
  'Čadca',
  'Dubnica nad Váhom',
  'Rimavská Sobota',
  'Partizánske',
  'Šaľa',
  'Dunajská Streda',
  'Vranov nad Topľou',
  'Pezinok',
  'Hlohovec',
  'Senica',
  'Brezno',
  'Malacky',
  'Senec',
  'Nové Mesto nad Váhom',
  'Snina',
  'Dolný Kubín',
  'Rožňava',
  'Púchov',
  'Žiar nad Hronom',
  'Banská Štiavnica',
  'Skalica',
  'Galanta',
  'Kežmarok',
  'Stará Ľubovňa',
];

/** Lowercase without diacritics, so "plzen" finds Plzeň. */
export function normalizeCity(s: string): string {
  return s.normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase().trim();
}

export const BUILT_IN_CITIES: string[] = [...new Set([...CZ, ...SK])];

/**
 * Up to `limit` cities for the typed text: names that start with it first, then names where a
 * word starts with it, then any match. Known cities (from existing gyms) are merged in.
 */
export function suggestCities(query: string, known: string[] = [], limit = 6): string[] {
  const q = normalizeCity(query);
  if (!q) return [];
  const seen = new Set<string>();
  const all: string[] = [];
  // Bundled names first, so their spelling wins over a differently typed duplicate.
  for (const c of [...BUILT_IN_CITIES, ...known]) {
    const name = c.trim();
    const key = normalizeCity(name);
    if (!name || seen.has(key)) continue;
    seen.add(key);
    all.push(name);
  }
  const rank = (c: string) => {
    const n = normalizeCity(c);
    if (n === q) return 0;
    if (n.startsWith(q)) return 1;
    if (n.split(/[\s-]+/).some((w) => w.startsWith(q))) return 2;
    if (n.includes(q)) return 3;
    return -1;
  };
  return all
    .map((c) => ({ c, r: rank(c) }))
    .filter((x) => x.r >= 0)
    .sort((a, b) => a.r - b.r || a.c.length - b.c.length || a.c.localeCompare(b.c, 'cs'))
    .slice(0, limit)
    .map((x) => x.c);
}
