-- Built-in exercises (created_by = null). Run after schema.sql.
insert into public.exercises (name, muscles, image_key) values
  ('Bench press', '{chest,triceps,shoulders}', 'bench-press'),
  ('Incline bench press', '{upper chest,triceps,shoulders}', null),
  ('Incline dumbbell press', '{upper chest,triceps}', null),
  ('Dumbbell bench press', '{chest,triceps}', null),
  ('Dips', '{chest,triceps}', null),
  ('Push-up', '{chest,triceps}', null),
  ('Overhead press', '{shoulders,triceps}', null),
  ('Dumbbell shoulder press', '{shoulders,triceps}', null),
  ('Lateral raise', '{shoulders}', null),
  ('Face pull', '{rear delts,upper back}', null),
  ('Triceps pushdown', '{triceps}', null),
  ('Skull crusher', '{triceps}', null),
  ('Squat', '{quads,glutes}', null),
  ('Front squat', '{quads}', null),
  ('Leg press', '{quads,glutes}', null),
  ('Lunge', '{quads,glutes}', null),
  ('Bulgarian split squat', '{quads,glutes}', null),
  ('Leg extension', '{quads}', null),
  ('Deadlift', '{back,glutes,hamstrings}', null),
  ('Romanian deadlift', '{hamstrings,glutes}', null),
  ('Leg curl', '{hamstrings}', null),
  ('Hip thrust', '{glutes}', null),
  ('Calf raise', '{calves}', null),
  ('Barbell row', '{back,biceps}', null),
  ('Dumbbell row', '{back,biceps}', null),
  ('Pull-up', '{back,biceps}', null),
  ('Chin-up', '{back,biceps}', null),
  ('Lat pulldown', '{back,biceps}', null),
  ('Seated cable row', '{back}', null),
  ('Shrug', '{traps}', null),
  ('Biceps curl', '{biceps}', null),
  ('Hammer curl', '{biceps,forearms}', null),
  ('Preacher curl', '{biceps}', null),
  ('Cable fly', '{chest}', null),
  ('Plank', '{core}', null),
  ('Hanging leg raise', '{core}', null),
  ('Cable crunch', '{core}', null),
  ('Farmer''s carry', '{grip,traps,core}', null),
  ('Good morning', '{hamstrings,lower back}', null),
  ('Arnold press', '{shoulders}', null);
