-- Built-in exercises (created_by = null). Run after schema.sql.
insert into public.exercises (name, muscles, image_key) values
  ('Bench press', '{chest,triceps,shoulders}', 'bench-press'),
  ('Incline bench press', '{upper chest,triceps,shoulders}', null),
  ('Incline dumbbell press', '{upper chest,triceps}', null),
  ('Dumbbell bench press', '{chest,triceps}', null),
  ('Dips', '{chest,triceps}', null),
  ('Push-up', '{chest,triceps}', null),
  ('Overhead press', '{shoulders,triceps}', null),
  ('Dumbbell shoulder press', '{shoulders,triceps}', null),
  ('Lateral raise', '{shoulders}', null),
  ('Face pull', '{rear delts,upper back}', null),
  ('Triceps pushdown', '{triceps}', null),
  ('Skull crusher', '{triceps}', null),
  ('Squat', '{quads,glutes}', null),
  ('Front squat', '{quads}', null),
  ('Leg press', '{quads,glutes}', null),
  ('Lunge', '{quads,glutes}', null),
  ('Bulgarian split squat', '{quads,glutes}', null),
  ('Leg extension', '{quads}', null),
  ('Deadlift', '{back,glutes,hamstrings}', null),
  ('Romanian deadlift', '{hamstrings,glutes}', null),
  ('Leg curl', '{hamstrings}', null),
  ('Hip thrust', '{glutes}', null),
  ('Calf raise', '{calves}', null),
  ('Barbell row', '{back,biceps}', null),
  ('Dumbbell row', '{back,biceps}', null),
  ('Pull-up', '{back,biceps}', null),
  ('Chin-up', '{back,biceps}', null),
  ('Lat pulldown', '{back,biceps}', null),
  ('Seated cable row', '{back}', null),
  ('Shrug', '{traps}', null),
  ('Biceps curl', '{biceps}', null),
  ('Hammer curl', '{biceps,forearms}', null),
  ('Preacher curl', '{biceps}', null),
  ('Cable fly', '{chest}', null),
  ('Plank', '{core}', null),
  ('Hanging leg raise', '{core}', null),
  ('Cable crunch', '{core}', null),
  ('Farmer''s carry', '{grip,traps,core}', null),
  ('Good morning', '{hamstrings,lower back}', null),
  ('Arnold press', '{shoulders}', null);

-- Jeff Nippard's S, A and B tier exercises (from his "Best and worst … exercises" tier lists).
-- Safe to run again: names that already exist are skipped.
insert into public.exercises (name, muscles)
select v.name, v.muscles::text[]
from (values
  ('Cable lateral raise', '{shoulders}'),
  ('Cable Y-raise', '{shoulders,rear delts}'),
  ('Behind-the-back cuffed cable lateral raise', '{shoulders}'),
  ('Reverse pec deck', '{rear delts,upper back}'),
  ('Reverse cable crossover', '{rear delts,upper back}'),
  ('Machine shoulder press', '{shoulders,triceps}'),
  ('Standing machine lateral raise', '{shoulders}'),
  ('Lean-in dumbbell lateral raise', '{shoulders}'),
  ('Side-lying dumbbell lateral raise', '{shoulders}'),
  ('Bent-over reverse dumbbell fly', '{rear delts,upper back}'),
  ('Seated machine lateral raise', '{shoulders}'),
  ('Lean-away dumbbell lateral raise', '{shoulders}'),
  ('Super-ROM dumbbell lateral raise', '{shoulders}'),
  ('Seated barbell overhead press', '{shoulders,triceps}'),
  ('Upright row', '{shoulders,traps}'),
  ('Hack squat', '{quads,glutes}'),
  ('Pendulum squat', '{quads,glutes}'),
  ('Smith machine squat', '{quads,glutes}'),
  ('Low-bar squat', '{quads,glutes,hamstrings}'),
  ('Reverse Nordic', '{quads}'),
  ('Goblet squat', '{quads,glutes}'),
  ('Sissy squat', '{quads}'),
  ('Machine chest press', '{chest,triceps,shoulders}'),
  ('Seated cable pec fly', '{chest}'),
  ('Deficit push-up', '{chest,triceps}'),
  ('Dumbbell guillotine press', '{chest,shoulders}'),
  ('Smith machine bench press', '{chest,triceps}'),
  ('Incline Smith machine bench press', '{upper chest,triceps}'),
  ('Cable crossover', '{chest}'),
  ('Pec deck', '{chest}'),
  ('Dumbbell fly', '{chest}'),
  ('Cable press-around', '{chest}'),
  ('Decline bench press', '{chest,triceps}'),
  ('Decline dumbbell press', '{chest,triceps}'),
  ('Banded push-up', '{chest,triceps}'),
  ('Neutral-grip lat pulldown', '{back,biceps}'),
  ('One-arm lat pulldown', '{back}'),
  ('Cross-body one-arm lat pulldown', '{back}'),
  ('Meadows row', '{back,rear delts}'),
  ('Chest-supported row', '{back,rear delts}'),
  ('Wide-grip cable row', '{upper back,rear delts}'),
  ('Neutral-grip pull-up', '{back,biceps}'),
  ('Deficit Pendlay row', '{back}'),
  ('Pendlay row', '{back}'),
  ('Kroc row', '{back,biceps,forearms}'),
  ('Cable lat prayer', '{back}'),
  ('Dumbbell pullover', '{back,chest}'),
  ('Overhead cable triceps extension', '{triceps}'),
  ('Katana cable triceps extension', '{triceps}'),
  ('One-arm dumbbell overhead extension', '{triceps}'),
  ('Dumbbell skull crusher', '{triceps}'),
  ('Smith machine JM press', '{triceps}'),
  ('JM press', '{triceps}'),
  ('Cable triceps kickback', '{triceps}'),
  ('Close-grip bench press', '{triceps,chest}'),
  ('Rope triceps pushdown', '{triceps}'),
  ('Dumbbell French press', '{triceps}'),
  ('Machine dips', '{triceps,chest}'),
  ('Diamond push-up', '{triceps,chest}'),
  ('Bayesian cable curl', '{biceps}'),
  ('Dumbbell preacher curl', '{biceps}'),
  ('Machine preacher curl', '{biceps}'),
  ('Preacher hammer curl', '{biceps,forearms}'),
  ('EZ-bar curl', '{biceps}'),
  ('Incline dumbbell curl', '{biceps}'),
  ('Lying dumbbell curl', '{biceps}'),
  ('Cable curl', '{biceps}'),
  ('Inverse Zottman curl', '{biceps,forearms}'),
  ('Barbell curl', '{biceps}'),
  ('Flat bench dumbbell curl', '{biceps}'),
  ('Walking lunge', '{glutes,quads}'),
  ('Machine hip abduction', '{glutes}'),
  ('45-degree back extension', '{glutes,hamstrings,lower back}'),
  ('Front-foot-elevated Smith machine lunge', '{glutes,quads}'),
  ('Smith machine lunge', '{glutes,quads}'),
  ('Machine hip thrust', '{glutes}'),
  ('Single-leg dumbbell hip thrust', '{glutes}'),
  ('Cable glute kickback', '{glutes}'),
  ('Step-up', '{glutes,quads}'),
  ('Glute bridge', '{glutes}'),
  ('Cable hip abduction', '{glutes}'),
  ('Curtsy lunge', '{glutes,quads}'),
  ('Sumo deadlift', '{glutes,quads,back}'),
  ('Cable pull-through', '{glutes,hamstrings}')
) as v(name, muscles)
where not exists (
  select 1 from public.exercises e where e.created_by is null and lower(e.name) = lower(v.name)
);
