/**
 * Links exercise illustrations to the app and lists the ones still missing.
 *
 *   npm run images
 *
 * 1. Drop a 16:9 image into assets/exercises/ named after the exercise, e.g. "hack-squat.jpg"
 *    (jpg, png or webp; about 1200×675 px and under ~150 kB keeps the app small).
 * 2. Run this script. It rewrites src/features/exercises/images.ts (the bundled image map) and
 *    docs/exercise-images.md (a ready-to-paste generator prompt for every exercise without one).
 */
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/(\w:)/, '$1')), '..');
const dir = path.join(root, 'assets/exercises');

export function slug(name) {
  return name
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/['’]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

// Built-in catalog: names + muscles from supabase/seed.sql.
const sql = fs.readFileSync(path.join(root, 'supabase/seed.sql'), 'utf8');
const catalog = [...sql.matchAll(/^\s+\('((?:[^']|'')+)', '\{([^}]*)\}'/gm)].map((m) => ({
  name: m[1].replace(/''/g, "'"),
  muscles: m[2].split(',').filter(Boolean),
}));

const files = fs.readdirSync(dir).filter((f) => /\.(jpe?g|png|webp)$/i.test(f)).sort();
const byKey = new Map(files.map((f) => [f.replace(/\.[^.]+$/, ''), f]));

const map = `/** Generated by \`npm run images\` from assets/exercises/. Do not edit by hand. */
export const EXERCISE_IMAGES: Record<string, number> = {
${[...byKey].map(([k, f]) => `  '${k}': require('../../../assets/exercises/${f}'),`).join('\n')}
};
`;
fs.writeFileSync(path.join(root, 'src/features/exercises/images.ts'), map);

const STYLE =
  'Photorealistic 3D render of a classical white-grey marble statue of a muscular athlete ' +
  '(Greco-Roman sculpture, curly hair and beard, a draped marble loincloth, visible veining in the stone) ' +
  'performing the exercise. All equipment is carved from the same marble. Three-quarter view from slightly above, ' +
  'whole body and equipment in frame with some margin, soft diffused studio light, gentle contact shadow, ' +
  'seamless plain light grey background (#DEDDDC), no text, no logos, no people other than the statue. ' +
  'Aspect ratio 16:9.';

const missing = catalog.filter((e) => !byKey.has(slug(e.name)));
const doc = `# Exercise illustrations

Style reference: \`assets/exercises/bench-press.jpg\` (marble statue, light grey background, 16:9).

**How to add one:** generate the image with the prompt below, save it as
\`assets/exercises/<file name>\` (jpg, png or webp, about 1200×675 px, under ~150 kB) and run \`npm run images\`.
Exercises without an image show a neutral placeholder of the same size.

${catalog.length - missing.length} of ${catalog.length} built-in exercises have an image. Missing: ${missing.length}.

## Style (shared by every prompt)

> ${STYLE}

## Missing images

| Exercise | File name | Prompt |
|---|---|---|
${missing
  .map(
    (e) =>
      `| ${e.name} | \`${slug(e.name)}.jpg\` | ${e.name} (works ${e.muscles.join(', ')}). ${STYLE} |`,
  )
  .join('\n')}
`;
fs.mkdirSync(path.join(root, 'docs'), { recursive: true });
fs.writeFileSync(path.join(root, 'docs/exercise-images.md'), doc);

console.log(`${files.length} image(s) linked; ${missing.length} of ${catalog.length} exercises still need one (see docs/exercise-images.md).`);
