/**
 * Exercise illustrations.
 *
 *   npm run images          link images in assets/exercises/ and write the ChatGPT prompts
 *   npm run images:import   take images downloaded from ChatGPT (assets/exercises/_inbox/),
 *                           name them, crop to 16:9, shrink, and link them
 *
 * Prompts go to docs/chatgpt-obrazky.md, in batches ready to paste into ChatGPT.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dir = path.join(root, 'assets/exercises');
const inbox = path.join(dir, '_inbox');
const BATCH = 15;
const OUT = { width: 1200, height: 675, quality: 80 };

/** Must match exerciseSlug() in src/lib/slug.ts. */
export function slug(name) {
  return name
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/['’]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

// Built-in catalog (names + muscles) from supabase/seed.sql, in seed order: the common lifts first.
// Prompts cover the curated list (core lifts + tier picks); the other ~1,200 catalog entries
// come from a dataset and get images later.
function catalog() {
  const all = JSON.parse(fs.readFileSync(path.join(root, 'src/data/exercises.json'), 'utf8'));
  return all.filter((e) => e.core);
}

const poses = JSON.parse(fs.readFileSync(path.join(root, 'scripts/exercise-poses.json'), 'utf8'));

function existingImages() {
  const files = fs
    .readdirSync(dir)
    .filter((f) => /\.(jpe?g|png|webp)$/i.test(f))
    .sort();
  return new Map(files.map((f) => [f.replace(/\.[^.]+$/, ''), f]));
}

function missing() {
  const have = existingImages();
  return catalog().filter((e) => !have.has(slug(e.name)));
}

const STYLE =
  'Photorealistic 3D render of a classical white-grey marble statue of a muscular male athlete ' +
  '(Greco-Roman sculpture with curly hair and a short beard, a draped marble loincloth, subtle veining in the stone). ' +
  'Every piece of equipment (bench, barbell, plates, dumbbells, machine, cables) is carved from the same pale marble. ' +
  'Three-quarter view from slightly above, the whole body and equipment in frame, ' +
  'soft diffused studio light with a gentle contact shadow, seamless plain light grey background (#DEDDDC). ' +
  'No text, no logos, no other people. ' +
  'Landscape 3:2 image; keep the statue and equipment within the middle 80 % of the width ' +
  'because the image will be cropped to 16:9.';

function writeLinks() {
  const have = existingImages();
  const map = `/** Generated by \`npm run images\` from assets/exercises/. Do not edit by hand. */
export const EXERCISE_IMAGES: Record<string, number> = {
${[...have].map(([k, f]) => `  '${k}': require('../../../assets/exercises/${f}'),`).join('\n')}
};
`;
  fs.writeFileSync(path.join(root, 'src/features/exercises/images.ts'), map);
  return have.size;
}

function writePrompts() {
  const all = catalog();
  const todo = missing();
  const batches = [];
  for (let i = 0; i < todo.length; i += BATCH) batches.push(todo.slice(i, i + BATCH));

  const batchText = (
    list,
    n,
  ) => `Generate ${list.length} exercise illustrations for a fitness app, one image per reply.
After each image, write only its number and file name, then wait until I write "next".

Style for every image (keep it identical across all of them):
${STYLE}
If I attached bench-press.jpg, treat it as the exact style reference.

${list
  .map(
    (e, i) =>
      `${i + 1}. ${slug(e.name)}.jpg | ${e.name}. Pose: ${poses[e.name] ?? `performing a ${e.name.toLowerCase()}`}.`,
  )
  .join('\n')}

Start with image 1.`;

  const doc = `# Obrázky cviků přes ChatGPT

Hotovo ${all.length - todo.length} z ${all.length}. Zbývá ${todo.length} obrázků v ${batches.length} dávkách po ${BATCH}.

## Jak na to

1. Otevři nový chat v ChatGPT a **přilož \`assets/exercises/bench-press.jpg\`** (vzor stylu).
2. Zkopíruj celý text **jedné dávky** níže (blok kódu, tlačítko „Copy“) a odešli.
3. Po každém obrázku napiš \`next\`. Každý obrázek hned stáhni (v pořadí 1, 2, 3…) do složky
   \`assets/exercises/_inbox/\`.
4. Když máš dávku staženou, spusť v PowerShellu ve složce projektu:

   \`\`\`powershell
   npm run images:import
   \`\`\`

   Obrázky se samy pojmenují podle pořadí, oříznou na 16:9, zmenší a napojí do aplikace.
   Tento soubor se pak přegeneruje jen se zbývajícími cviky.

Tipy:
- Pořadí stahování = pořadí v dávce. Když nějaký obrázek přeskočíš, přejmenuj zbylé soubory
  ručně na název z dávky (např. \`hack-squat.png\`) – pojmenované soubory import pozná sám.
- Když se obrázek nepovede, napiš ChatGPT \`redo\` a stáhni až opravenou verzi.
- Na jednu dávku je nejlepší nový chat, styl pak zůstává stejný.

${batches
  .map(
    (list, n) => `## Dávka ${n + 1} z ${batches.length}

\`\`\`text
${batchText(list, n)}
\`\`\`
`,
  )
  .join('\n')}`;
  fs.writeFileSync(path.join(root, 'docs/chatgpt-obrazky.md'), doc);
  const old = path.join(root, 'docs/exercise-images.md');
  if (fs.existsSync(old)) fs.rmSync(old);
  return { todo: todo.length, batches: batches.length };
}

async function importInbox() {
  const sharp = (await import('sharp')).default;
  if (!fs.existsSync(inbox)) fs.mkdirSync(inbox, { recursive: true });
  const files = fs
    .readdirSync(inbox)
    .filter((f) => /\.(jpe?g|png|webp)$/i.test(f))
    .map((f) => ({ f, t: fs.statSync(path.join(inbox, f)).mtimeMs }))
    .sort((a, b) => a.t - b.t)
    .map((x) => x.f);
  if (files.length === 0) {
    console.log(
      `No images in ${path.relative(root, inbox)}. Download them there from ChatGPT first.`,
    );
    return;
  }
  const queue = missing().map((e) => slug(e.name));
  const named = new Set(
    files.map((f) => f.replace(/\.[^.]+$/, '')).filter((k) => queue.includes(k)),
  );
  const order = queue.filter((k) => !named.has(k));
  const rows = [];
  for (const f of files) {
    const base = f.replace(/\.[^.]+$/, '');
    const key = named.has(base) ? base : order.shift();
    if (!key) {
      rows.push([f, '(skipped: every exercise already has an image)']);
      continue;
    }
    const out = path.join(dir, `${key}.jpg`);
    await sharp(path.join(inbox, f))
      .resize(OUT.width, OUT.height, { fit: 'cover', position: 'centre' })
      .jpeg({ quality: OUT.quality, mozjpeg: true })
      .toFile(out);
    fs.rmSync(path.join(inbox, f));
    rows.push([f, `${key}.jpg (${Math.round(fs.statSync(out).size / 1024)} kB)`]);
  }
  console.log('Imported:');
  for (const [from, to] of rows) console.log(`  ${from}  ->  ${to}`);
  console.log(
    'Check the names above. A wrong one? Rename the file in assets/exercises/ and run npm run images.',
  );
}

if (process.argv.includes('--import')) await importInbox();
const linked = writeLinks();
const { todo, batches } = writePrompts();
console.log(
  `${linked} image(s) linked; ${todo} exercises still need one (${batches} ChatGPT batches in docs/chatgpt-obrazky.md).`,
);
