/** Generated by `npm run images` from assets/exercises/. Do not edit by hand. */
export const EXERCISE_IMAGES: Record<string, number> = {
  'bench-press': require('../../../assets/exercises/bench-press.jpg'),
};
